"""evolve check_ins for mood/connection scores

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-04 12:02:12.981912
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_ins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('mood_score', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('connection_score', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
        batch_op.alter_column('couple_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_check_ins_date'), ['date'], unique=False)
        batch_op.create_unique_constraint('uq_check_in_user_date', ['user_id', 'date'])
        batch_op.drop_column('message')
        batch_op.drop_column('mood')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_ins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mood', sa.VARCHAR(length=40), nullable=False))
        batch_op.add_column(sa.Column('message', sa.TEXT(), nullable=True))
        batch_op.drop_constraint('uq_check_in_user_date', type_='unique')
        batch_op.drop_index(batch_op.f('ix_check_ins_date'))
        batch_op.alter_column('couple_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('note')
        batch_op.drop_column('tags')
        batch_op.drop_column('connection_score')
        batch_op.drop_column('mood_score')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
